export const ActionTypes = {
  signupUser: 'SIGNUP_USER',
  getCurrentSession: 'GET_CURRENT_SESSION',
  getCurrentCredentials: 'GET_CURRENT_CREDENTIALS',
  confirmSignUp: 'CONFIRM_SIGNUP_USER',
  listUserAccounts: 'LIST_USER_ACCOUNTS',
  loginUser: 'LOGIN_USER',
  tempLoginUser: 'TEMP_LOGIN_USER',
  logoutUser: 'LOGOUT_USER',
  forgotPassword: 'FORGOT_PASSWORD',
  forgotPasswordSubmit: 'FORGOT_PASSWORD_SUBMIT',
  changePassword: 'CHANGE_PASSWORD',
  updateCurrentUser: 'UPDATE_CURRENT_USER',
  getCogAuthUser: 'GET_COGNITO_AUTH_USER',
  getCurrentDBUser: 'GET_CURRENT_DB_USER',
  updateCognitoPw: 'UPDATE_COGNITO_PASSWORD',
  deleteUser: 'DELETE_USER',
  cognitoResendEmail: 'COGNITO_RESEND_EMAIL',
  resetErrorState: 'RESET_ERROR_STATE',
  updateUserAccount: 'UPDATE_USER_ACCOUNT',
}
